name: Build cores
on:
  schedule:
    - cron: '37 3 * * 6'
  workflow_dispatch:
jobs:
  build:
    name: Build cores
    runs-on: ubuntu-latest
    container: node:current-buster-slim
    steps:
      - name: Get latest version
        run: |
          apt-get update
          apt-get install --assume-yes curl git
          git clone --branch main --single-branch https://github.com/cjom/libretro_cores_linux_armhf.git
          tag_version=$(curl -fs https://github.com/libretro/mame/tags | grep -m1 'libretro/mame/commit/' | sed -e 's:^.*libretro/mame/commit/::' -e 's:">.*::')
          tag_name=$(curl -fs https://github.com/libretro/mame/tags | grep -m1 'libretro/mame/releases/tag/' | sed -e 's:^.*libretro/mame/releases/tag/::' -e 's:".*::')
          echo "tag_version=$tag_version" >> "$GITHUB_ENV"
          echo "tag_name=$tag_name" >> "$GITHUB_ENV"
          echo "tag_name=$tag_name"
          echo "tag_version=$tag_version"
          if [ -e "libretro_cores_linux_armhf/cores_armhf/mame_libretro_${tag_name}.zip" ]
          then
            echo "libretro_cores_linux_armhf/cores_armhf/mame_libretro.${tag_name}.zip already exists."
            exit
          fi
      - name: Install tools
        run: |
          apt-get install --assume-yes ca-certificates build-essential zip python3 xfonts-utils xsltproc default-jre unzip xz-utils texi2html texinfo
          apt-get install --assume-yes libxml-parser-perl libparse-yapp-perl libjson-perl libncurses5-dev bc gawk wget zstd gperf lzop patchutils sudo
          apt-get install --assume-yes aria2 autoconf automake bison bzip2 coreutils flex g++ gcc gzip help2man libtool libtool-bin make p7zip p7zip-full rsync
      - name: compile core
        run: |
          git clone https://github.com/cjom/Lakka-LibreELEC.git
          cd Lakka-LibreELEC
          sed -i -e "/.*PKG_VERSION\=.*/{s//PKG_VERSION=\"${tag_version}\"/;:a" -e '$!N;$!ba' -e '}' packages/lakka/libretro_cores/mame/package.mk
          GIT_DISCOVERY_ACROSS_FILESYSTEM=1 CCACHE_DISABLE=1 DISTRO=Lakka PROJECT=Allwinner DEVICE=H3 ARCH=arm UBOOT_SYSTEM=capcom-home-arcade scripts/build lakka/libretro_cores/mame
          mkdir ../libretro_cores_linux_armhf/cores_armhf
          find . -name 'mamearcade_libretro.so' -type f -exec mv {} ./mame_libretro.so \;
          zip -9 ../libretro_cores_linux_armhf/cores_armhf/mame_libretro.${tag_name}.zip mame_libretro.so
          cd ../libretro_cores_linux_armhf
          git add . && git commit -m "New core compiled: ${tag_name}" && git push
